### PR TITLE
internationalisation of wbounce plugin files

### PR DESCRIPTION
**Pull request by senlin**
All options (settings) and documentation is now internationalised and can be translated.

Call for textdomain (wbounce) still needs to be added.

### CODE REVIEW

**Comment by kevinweber** [comment]
Hi @senlin,
great thanks for your contribution!
Would you also like to provide a language file?
Best regards,
Kevin

**Comment by senlin** [comment]
Hi @kevinweber 

First we need to add a function that adds the textdomain `wbounce` to the plugin. I'm not sure how you want to tackle that, that's why I haven't included it in my previous PR. You can have a look how I do it with my plugins, for example here: [add_action](https://github.com/senlin/so-dashboard-feed-widget/blob/master/dashboard-feed-widget.php#L107-L108) and [actual function](https://github.com/senlin/so-dashboard-feed-widget/blob/master/dashboard-feed-widget.php#L154-L163)

I can generate the initial .po file once you have included the textdomain function and then I will have to see whether I have time to translate the lot to Dutch. 

But the most important job (internationalisation of the plugin so it can be used by the other 52% of the web) is done at least...

Cheers,
Piet

**Comment by kevinweber** [comment]
Ok, great!
I just included the text domain function (75db06003bcb538b5dcb6da7e020ddef0575766a).
Now you can add a 'languages' folder with the initial translation files. I'll also provide a German translation before I publish the updated plugin in the midst of July.
– Kevin

**Comment by senlin** [comment]
I fail to see where you define `WBOUNCE_TD`... maybe I looked to fast?

**Comment by kevinweber** [comment]
It's defined in wbounce.php (https://github.com/kevinweber/wbounce/blob/master/wbounce.php#L30).

**Comment by senlin** [comment]
cool, thanks

**Pull request merged**
